flashcard/config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  resources :flashcard_set, :only => [:index, :show] do
    resources :card, :only => [:show, :index]
  end

end

flashcard/app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :flashcard_set
end

flashcard/app/models/flashcard_set.rb
class FlashcardSet < ActiveRecord::Base
	has_many :cards
end

flashcard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include CardHelper
end

flashcard/app/controllers/card_controller.rb
class CardController < ApplicationController

	def show
		@set = FlashcardSet.find(params[:flashcard_set_id])
		@card = Card.find(params[:id])
		@card_ids = @set.cards.map(&:id).shuffle!
		@first_card = @set.cards.order(:id).first.id
	end

end

flashcard/app/controllers/flashcard_set_controller.rb
class FlashcardSetController < ApplicationController
	def index
		@flashcard_sets = FlashcardSet.all
	end

	def show
		@flashcard_set = FlashcardSet.find(params[:id])
		@first_card = @flashcard_set.cards.order(:id).first.id
		@card_ids = @flashcard_set.cards.map(&:id).shuffle!
		session[:cards] = @card_ids
	end
end

flashcard/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

flashcard/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		redirect_to flashcard_set_index_path
	end
end

flashcard/app/helpers/application_helper.rb
module ApplicationHelper
end

flashcard/app/helpers/card_helper.rb
module CardHelper

	def next_card
		if @card_ids.include?(@card.id + 1) 
			@card.id + 1 
		else
			@first_card
		end
	end

	def card_pop
		session[:cards].pop
	end

	def reshuffle
		redirect_to flashcard_set_path(@set) if session[:cards] == nil	
	end

	def next_random_card
		reshuffle
		card_pop unless session[:cards] == nil
	end
end

flashcard/app/helpers/flashcard_set_helper.rb
module FlashcardSetHelper
	def random_first_card
		session[:cards].pop
	end
end

flashcard/app/helpers/sessions_helper.rb
module SessionsHelper
	
end

flashcard/app/helpers/welcome_helper.rb
module WelcomeHelper
end

flashcard/app/views/card/show.html.erb
<div class="container">
	<div class="content">
		<h1 class="card_title"><%= @set.name %></h1>
		<% if @set.name == "Math" %>
			<p class="numbers"><%=rand(1..5).to_s + " + " + rand(1..5).to_s%></p>
			<%= link_to "<div class='arrow_right'></div>".html_safe, "" %>
		<% elsif @set.name == "Alphabet" %>
			<p class="alphabet"><%= @card.text %></p>
			<img src="<%= @card.image_url %>">
		<% elsif @card.image_url %>
			<p><%= @card.text %></p>
			<img src="<%= @card.image_url %>">
		<% else %>
			<p class="big_words"><%= @card.text %></p>
		<% end %>
				
		
		<% if @set.name != "Math" %>
			<%= link_to "<div class='arrow_right'></div>".html_safe, flashcard_set_card_path(@set, next_card), id: "next_card"%>
		<% end %>
	</div>
</div>

flashcard/app/views/flashcard_set/index.html.erb
<div class="set_index">	
	<ul class="thumbs">
		<% @flashcard_sets.each do |set| %>
				<li class = "deck_index">
					<p class="index_title"><%= link_to set.name , flashcard_set_path(set), class: "pop" %></p>
					<a href="/flashcard_set/<%= set.id %>"><img class="buzz-out" src="<%=set.image_url%>"></a><br>
				</li>
		<% end %>
	</ul>
</div>

flashcard/app/views/flashcard_set/show.html.erb
<div class="container">
	<div class="content">
		<h1><%= @flashcard_set.name %></h1>
		<img src="<%= @flashcard_set.image_url %>">
		<h2><%= link_to "<div class='arrow_right'></div>".html_safe, flashcard_set_card_path(@flashcard_set, @first_card ) %></h2>

	</div>
</div>

flashcard/app/views/layouts/_footer.html.erb
<p class="credit_disclaimer">
	<a href="https://twitter.com/statusd0">@statusdo</a><br>
	A Ricky D. production<br>
	All images used were from public domains.</p>

flashcard/app/views/layouts/_header.html.erb
<div class="header">
	<ul>
		<li><%=link_to '<i class="fa fa-home"></i>'.html_safe, root_path, class: "grow" %></li>
		<li><h1 id="title" class="shadow-radial">Flashcards for the Littles</h1></li>
	</ul>
</div>

flashcard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" >
  <%= stylesheet_link_tag    'application'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>